spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: <You API Key here>
      embedding-model:
        model-name: text-embedding-v3
        api-key: <You API Key here>
rag:
  docs-path: src/main/resources/docs
  split-size: 1000
  split-overlap: 200
  max-results: 5
  min-score: 0.75
